language: rust

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - texinfo
      - libgif-dev
      - libxmp-dev
      - libgnutls28-dev

  homebrew:
    packages:
      - gnutls
      - texinfo

cache:
  cargo: true
  directories:
    - $HOME/.rustup

env:
  - CHECKS=glyphs
  - CHECKS=

stages:
  - rustfmt
  - clippy
  - test

allow_failures:
  - os: osx
  - os: windows
  - stage: clippy

matrix:
  fast_finish: true

jobs:
  include:
    - stage: rustfmt
      name: "Ensure code is formatted"
      script:
        - echo rustfmt
        - printenv
    - stage: clippy
      name: "Run Clippy checks"
      script:
        - echo clippy
        - printenv
    - stage: test
      name: "Run tests"
      script:
        - echo test
        - printenv
