language: rust

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - texinfo
      - libgif-dev
      - libxmp-dev
      - libgnutls28-dev

  homebrew:
    packages:
      - gnutls
      - texinfo

cache:
  cargo: true
  directories:
    - $HOME/.rustup

env:
  global:
    - RUST_BACKTRACE=1
    - CARGO_FLAGS="--features strict"
  matrix:
    - CHECKS=
    - CHECKS=glyphs
    - WINDOW_SYSTEM=0
    - WINDOW_SYSTEM=1

stages:
  - rustfmt
  - clippy
  - test

allow_failures:
  - os: osx
  - os: windows
  - stage: clippy

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: WINDOW_SYSTEM=0
    - os: windows
      env: WINDOW_SYSTEM=0
    - env:
        - WINDOW_SYSTEM=0
        - CHECKS=glyphs

jobs:
  include:

    - stage: rustfmt
      os: linux
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add rustfmt
      script:
        - printenv

    - stage: clippy
      os: linux
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
        - travis_wait rustup component add clippy
      script:
        - printenv

    - stage: test
      before_script:
        - travis_wait rustup install $(cat rust-toolchain)
      script:
        - printenv
