language: rust

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - texinfo
      - libgif-dev
      - libxmp-dev
      - libgnutls28-dev

  homebrew:
    packages:
      - gnutls
      - texinfo

cache:
  cargo: true
  directories:
    - $HOME/.rustup

env:
  global:
    - RUST_BACKTRACE=1
    - CARGO_FLAGS="--features strict"
  matrix:
    - CHECKING=no WINDOW_SYSTEM=no
    - CHECKING=glyphs WINDOW_SYSTEM=no
    - CHECKING=no WINDOW_SYSTEM=yes
    - CHECKING=glyphs WINDOW_SYSTEM=yes

stages:
  - rustfmt
  - clippy
  - test

jobs:
  include:

    - stage: rustfmt
      os: linux
      install:
        - travis_wait rustup component add rustfmt
      before_script:
        - ./autogen.sh && ./configure --without-all
      script:
        - ./.travis-format.sh

    - stage: clippy
      os: linux
      install:
        - travis_wait rustup component add clippy
      before_script:
        - ./autogen.sh && ./configure --without-all
      script:
        - make clippy

matrix:
  fast_finish: true

  allow_failures:
    - os: osx
    - os: windows
    - stage: clippy

  exclude:
    - os: osx
      env: CHECKING=no WINDOW_SYSTEM=no
    - os: osx
      env: CHECKING=glyphs WINDOW_SYSTEM=no
    - os: windows
      env: CHECKING=no WINDOW_SYSTEM=no
    - os: windows
      env: CHECKING=glyphs WINDOW_SYSTEM=no

  include:
    - &linux-with-x
      os: linux
      env: CHECKING=no WINDOW_SYSTEM=yes
      addons: {apt: {packages: [libgtk3-dev]}}
    -
      <<: *linux-with-x
      env: CHECKING=glyphs WINDOW_SYSTEM=yes

before_script:
  - test "$WINDOW_SYSTEM" = "yes" && CONFIGURE_FLAGS='--without-makeinfo --with-x=no --with-ns=no --without-gconf --without-gsettings'
  - >
    ./autogen.sh &&
    ./configure $CONFIGURE_FLAGS \
                RUSTFLAGS="-Dwarnings" \
                WERROR_CFLAGS='-Werror -Wno-error=deprecated-declarations'

script:
  - printenv
